#!/usr/bin/env python
"""
Pack analysis tables into a single Excel workbook (Supplementary Data 1).

This script is intentionally "dumb": it does not recompute anything.
It reads CSV files in a tables directory and writes each one to a sheet.

Important manuscript-alignment note
-----------------------------------
JMP-derived variable clustering was performed in JMP Pro 17 and is reported
separately in the Supplementary Tables. Python approximate variable-clustering
CSV outputs are intentionally excluded from Supplementary Data 1 to avoid
mixing JMP-derived and Python-approximate summaries.

Backwards-compatible args:
  --input-dir /path/to/tables   (alias: --tables-dir)
  --output /path/to.xlsx        (alias: --out-xlsx)
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re

import pandas as pd


# Python approximate variable-clustering outputs are excluded from the workbook.
# The authoritative JMP-derived variable-clustering result is reported in the
# Supplementary Tables, not regenerated by this Python no-figure pipeline.
EXCLUDE_STEM_PATTERNS = (
    "varcluster",
    "variable_clustering",
)


def safe_sheet_name(name: str) -> str:
    """Return an Excel-safe sheet name: <=31 chars, no []:*?/\\."""
    name = re.sub(r"[\[\]\:\*\?\/\\]", "_", name)
    return name[:31]


def should_exclude_csv(path: Path) -> bool:
    """Return True for CSVs that should not be packed into Supplementary Data 1."""
    stem = path.stem.lower()
    return any(pattern in stem for pattern in EXCLUDE_STEM_PATTERNS)


def make_unique_sheet_name(base: str, used: set[str]) -> str:
    """Avoid rare Excel sheet-name collisions after truncation/sanitization."""
    base = safe_sheet_name(base)
    if base not in used:
        used.add(base)
        return base

    for i in range(1, 1000):
        suffix = f"_{i}"
        candidate = f"{base[:31 - len(suffix)]}{suffix}"
        if candidate not in used:
            used.add(candidate)
            return candidate

    raise RuntimeError(f"Could not create unique sheet name for: {base}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input-dir", default=None, help="Directory containing CSV tables (legacy arg).")
    ap.add_argument("--tables-dir", default=None, help="Directory containing CSV tables.")
    ap.add_argument("--output", default=None, help="Output .xlsx path (legacy arg).")
    ap.add_argument("--out-xlsx", default=None, help="Output .xlsx path.")
    args = ap.parse_args()

    tables_dir = Path(args.tables_dir or args.input_dir or ".").resolve()
    out_xlsx = Path(args.out_xlsx or args.output or "supplementary_data_1_generated.xlsx").resolve()

    if not tables_dir.exists():
        raise SystemExit(f"[ERROR] tables dir not found: {tables_dir}")

    all_csvs = sorted(tables_dir.glob("*.csv"))
    skipped_csvs = [p for p in all_csvs if should_exclude_csv(p)]
    csvs = [p for p in all_csvs if not should_exclude_csv(p)]

    if not all_csvs:
        raise SystemExit(f"[ERROR] no CSV files found in: {tables_dir}")

    if not csvs:
        skipped_names = ", ".join(p.name for p in skipped_csvs)
        raise SystemExit(
            "[ERROR] all CSV files were excluded from workbook export. "
            f"Skipped files: {skipped_names}"
        )

    out_xlsx.parent.mkdir(parents=True, exist_ok=True)

    used_sheet_names: set[str] = set()
    index_rows = []

    with pd.ExcelWriter(out_xlsx, engine="openpyxl") as xw:
        for p in csvs:
            df = pd.read_csv(p)
            sheet = make_unique_sheet_name(p.stem, used_sheet_names)

            index_rows.append(
                {
                    "sheet": sheet,
                    "file": p.name,
                    "rows": len(df),
                    "cols": len(df.columns),
                }
            )

            df.to_excel(xw, sheet_name=sheet, index=False)

        pd.DataFrame(index_rows).to_excel(xw, sheet_name="INDEX", index=False)

    print(f"[OK] Wrote: {out_xlsx}")

    if skipped_csvs:
        print("[INFO] Excluded from workbook export:")
        for p in skipped_csvs:
            print(f"  - {p.name}")


if __name__ == "__main__":
    main()
